# Get L1000 Genes

April 16th 2026

We had the unfortunate realization that we have 18k training, 2k val/test samples and with that we will have issues predicting 20k outputs. To combat that we will compress the output to the L1000 gene set and compare the final pertubertaion state and predicted state on these 1k genes (actually 978)

L1000 takes some landmark genes that are a fairly accurate representation of cell state so on that basis, we should be able to make and compare predictions on these 1k genes. 

Soure: Subramanian A, Narayan R, Corsello SM, Peck DD, Natoli TE, Lu X, Gould J, Davis JF, Tubelli AA, Asiedu JK, Lahr DL. A next generation connectivity map: L1000 platform and the first 1,000,000 profiles. Cell. 2017 Nov 30;171(6):1437-52.

# Import packages and files

In [4]:
import pandas as pd

data_path = "../data/geneinfo_beta.txt"
geneinfo_df = pd.read_csv(data_path, sep="\t")
geneinfo_df.head()

,gene_id,gene_symbol,ensembl_id,gene_title,gene_type,src,feature_space
0,750,GAS8-AS1,ENSG00000221819,GAS8 antisense RNA 1,ncRNA,NCBI,inferred
1,6315,ATXN8OS,NaN,ATXN8 opposite strand lncRNA,ncRNA,NCBI,inferred
2,7503,XIST,ENSG00000229807,X inactive specific transcript,ncRNA,NCBI,inferred
3,8552,INE1,ENSG00000224975,inactivation escape 1,ncRNA,NCBI,inferred
4,9834,FAM30A,ENSG00000226777,family with sequence similarity 30 member A,ncRNA,NCBI,inferred

In [11]:
landmark_genes = geneinfo_df[geneinfo_df["feature_space"]== "landmark"]
landmark_genes = landmark_genes[["ensembl_id", "gene_symbol", 'gene_title']]
landmark_genes

,ensembl_id,gene_symbol,gene_title
2154,ENSG00000090861,AARS,alanyl-tRNA synthetase
2155,ENSG00000204574,ABCF1,ATP binding cassette subfamily F member 1
2156,ENSG00000097007,ABL1,"ABL proto-oncogene 1, non-receptor tyrosine ki..."
2157,ENSG00000060971,ACAA1,acetyl-CoA acyltransferase 1
2158,ENSG00000120437,ACAT2,acetyl-CoA acetyltransferase 2
...,...,...,...
3127,ENSG00000084652,TXLNA,taxilin alpha
3128,ENSG00000198369,SPRED2,sprouty related EVH1 domain containing 2
3129,ENSG00000149499,EML3,EMAP like 3
3130,ENSG00000213533,STIMATE,STIM activating enhancer
3131,ENSG00000154511,DIPK1A,divergent protein kinase domain 1A

In [ ]:
save_file = False
if save_file:
    landmark_genes.to_csv("../data/landmark_genes.csv", index=False)